# Welcome to Jekyll!
#

# Site settings
title: AXL * Memory * YZC
description: |
  关于我们  
  遇见你是最大的幸运  
  一万年太久，只争朝夕
owner: AXitakaL # or company name
first_published: 2016 # if migrating another site, the year of your first publish
email: 511899700@qq.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://AXitakaL.github.io" # the base hostname & protocol for your site
social:
  #twitter: https://twitter.com/<username>
  github: https://github.com/AXitakaL
  #linkedin-square: https://linkedin.com/in/<username>
  #facebook-official: https://facebook.com/<username>
  #google-plus-square: https://plus.google.com/u/0/+<username>
  #email: /contact/
  #flickr:
  instagram: https://www.instagram.com/holmesin
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  weibo: http://www.weibo.com/holmesin
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed
